// flow-typed signature: 711979c8af5165993f1ec5894ae94bb5
// flow-typed version: <<STUB>>/nodep-date-input-polyfill_v^5.2.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodep-date-input-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodep-date-input-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodep-date-input-polyfill/input' {
  declare module.exports: any;
}

declare module 'nodep-date-input-polyfill/locales' {
  declare module.exports: any;
}

declare module 'nodep-date-input-polyfill/nodep-date-input-polyfill.dist' {
  declare module.exports: any;
}

declare module 'nodep-date-input-polyfill/nodep-date-input-polyfill' {
  declare module.exports: any;
}

declare module 'nodep-date-input-polyfill/picker' {
  declare module.exports: any;
}

declare module 'nodep-date-input-polyfill/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodep-date-input-polyfill/input.js' {
  declare module.exports: $Exports<'nodep-date-input-polyfill/input'>;
}
declare module 'nodep-date-input-polyfill/locales.js' {
  declare module.exports: $Exports<'nodep-date-input-polyfill/locales'>;
}
declare module 'nodep-date-input-polyfill/nodep-date-input-polyfill.dist.js' {
  declare module.exports: $Exports<'nodep-date-input-polyfill/nodep-date-input-polyfill.dist'>;
}
declare module 'nodep-date-input-polyfill/nodep-date-input-polyfill.js' {
  declare module.exports: $Exports<'nodep-date-input-polyfill/nodep-date-input-polyfill'>;
}
declare module 'nodep-date-input-polyfill/picker.js' {
  declare module.exports: $Exports<'nodep-date-input-polyfill/picker'>;
}
declare module 'nodep-date-input-polyfill/rollup.config.js' {
  declare module.exports: $Exports<'nodep-date-input-polyfill/rollup.config'>;
}
