// flow-typed signature: dd66afd6dc799db7d16619374bfc5cfb
// flow-typed version: <<STUB>>/react-flatpickr_v^3.1.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-flatpickr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-flatpickr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-flatpickr/build/example' {
  declare module.exports: any;
}

declare module 'react-flatpickr/build/index' {
  declare module.exports: any;
}

declare module 'react-flatpickr/example/index' {
  declare module.exports: any;
}

declare module 'react-flatpickr/example/webpack' {
  declare module.exports: any;
}

declare module 'react-flatpickr/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-flatpickr/build/example.js' {
  declare module.exports: $Exports<'react-flatpickr/build/example'>;
}
declare module 'react-flatpickr/build/index.js' {
  declare module.exports: $Exports<'react-flatpickr/build/index'>;
}
declare module 'react-flatpickr/example/index.js' {
  declare module.exports: $Exports<'react-flatpickr/example/index'>;
}
declare module 'react-flatpickr/example/webpack.js' {
  declare module.exports: $Exports<'react-flatpickr/example/webpack'>;
}
declare module 'react-flatpickr/lib/index.js' {
  declare module.exports: $Exports<'react-flatpickr/lib/index'>;
}
