// flow-typed signature: 29af323382d9d59ec89968d9e61661e3
// flow-typed version: <<STUB>>/react-table_v^6.7.5/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-table/lib/defaultProps' {
  declare module.exports: any;
}

declare module 'react-table/lib/hoc/selectTable/index' {
  declare module.exports: any;
}

declare module 'react-table/lib/hoc/treeTable/index' {
  declare module.exports: any;
}

declare module 'react-table/lib/index' {
  declare module.exports: any;
}

declare module 'react-table/lib/lifecycle' {
  declare module.exports: any;
}

declare module 'react-table/lib/methods' {
  declare module.exports: any;
}

declare module 'react-table/lib/pagination' {
  declare module.exports: any;
}

declare module 'react-table/lib/propTypes' {
  declare module.exports: any;
}

declare module 'react-table/lib/utils' {
  declare module.exports: any;
}

declare module 'react-table/react-table' {
  declare module.exports: any;
}

declare module 'react-table/src/defaultProps' {
  declare module.exports: any;
}

declare module 'react-table/src/hoc/selectTable/index' {
  declare module.exports: any;
}

declare module 'react-table/src/hoc/treeTable/index' {
  declare module.exports: any;
}

declare module 'react-table/src/index' {
  declare module.exports: any;
}

declare module 'react-table/src/lifecycle' {
  declare module.exports: any;
}

declare module 'react-table/src/methods' {
  declare module.exports: any;
}

declare module 'react-table/src/pagination' {
  declare module.exports: any;
}

declare module 'react-table/src/propTypes' {
  declare module.exports: any;
}

declare module 'react-table/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-table/lib/defaultProps.js' {
  declare module.exports: $Exports<'react-table/lib/defaultProps'>;
}
declare module 'react-table/lib/hoc/selectTable/index.js' {
  declare module.exports: $Exports<'react-table/lib/hoc/selectTable/index'>;
}
declare module 'react-table/lib/hoc/treeTable/index.js' {
  declare module.exports: $Exports<'react-table/lib/hoc/treeTable/index'>;
}
declare module 'react-table/lib/index.js' {
  declare module.exports: $Exports<'react-table/lib/index'>;
}
declare module 'react-table/lib/lifecycle.js' {
  declare module.exports: $Exports<'react-table/lib/lifecycle'>;
}
declare module 'react-table/lib/methods.js' {
  declare module.exports: $Exports<'react-table/lib/methods'>;
}
declare module 'react-table/lib/pagination.js' {
  declare module.exports: $Exports<'react-table/lib/pagination'>;
}
declare module 'react-table/lib/propTypes.js' {
  declare module.exports: $Exports<'react-table/lib/propTypes'>;
}
declare module 'react-table/lib/utils.js' {
  declare module.exports: $Exports<'react-table/lib/utils'>;
}
declare module 'react-table/react-table.js' {
  declare module.exports: $Exports<'react-table/react-table'>;
}
declare module 'react-table/src/defaultProps.js' {
  declare module.exports: $Exports<'react-table/src/defaultProps'>;
}
declare module 'react-table/src/hoc/selectTable/index.js' {
  declare module.exports: $Exports<'react-table/src/hoc/selectTable/index'>;
}
declare module 'react-table/src/hoc/treeTable/index.js' {
  declare module.exports: $Exports<'react-table/src/hoc/treeTable/index'>;
}
declare module 'react-table/src/index.js' {
  declare module.exports: $Exports<'react-table/src/index'>;
}
declare module 'react-table/src/lifecycle.js' {
  declare module.exports: $Exports<'react-table/src/lifecycle'>;
}
declare module 'react-table/src/methods.js' {
  declare module.exports: $Exports<'react-table/src/methods'>;
}
declare module 'react-table/src/pagination.js' {
  declare module.exports: $Exports<'react-table/src/pagination'>;
}
declare module 'react-table/src/propTypes.js' {
  declare module.exports: $Exports<'react-table/src/propTypes'>;
}
declare module 'react-table/src/utils.js' {
  declare module.exports: $Exports<'react-table/src/utils'>;
}
