// flow-typed signature: 70f9e3785fb1402cbe31d0fd830b9bd4
// flow-typed version: <<STUB>>/twix_v^1.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'twix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'twix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'twix/dist/twix' {
  declare module.exports: any;
}

declare module 'twix/dist/twix.min' {
  declare module.exports: any;
}

declare module 'twix/package' {
  declare module.exports: any;
}

// Filename aliases
declare module 'twix/dist/twix.js' {
  declare module.exports: $Exports<'twix/dist/twix'>;
}
declare module 'twix/dist/twix.min.js' {
  declare module.exports: $Exports<'twix/dist/twix.min'>;
}
declare module 'twix/package.js' {
  declare module.exports: $Exports<'twix/package'>;
}
